const LOGIN_USER = "LOGIN_USER";
const LOGOUT_USER = "LOGOUT_USER";
const UPDATE_USER = "UPDATE_USER";

const FETCH_ITEM = "FETCH_ITEM";
const ADD_ITEM = "ADD_ITEM";
const DELETE_ITEM = "DELETE_ITEM";

const UPDATE_ITEM = "UPDATE_ITEM";
const ORDER_PLACED = "ORDER_PLACED";
const RESET_ORDER = "RESET_ORDER";

const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const VIEW_PRODUCT = "VIEW_PRODUCT";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export {
  LOGIN_USER,
  LOGOUT_USER,
  UPDATE_USER,
  FETCH_ITEM,
  ADD_ITEM,
  DELETE_ITEM,
  UPDATE_ITEM,
  ORDER_PLACED,
  RESET_ORDER,
  FETCH_PRODUCTS,
  DELETE_PRODUCT,
  VIEW_PRODUCT,
  UPDATE_PRODUCT,
};
